### ISSUE TITLE
All downloaded mp3 get corrupted

### ISSUE THREAD

**Issue by garlik82** [LizardByte/Themerr-jellyfin#97] opened 2023-09-15 08:55 UTC
### Describe the Bug

Plugin works fine, creates Themerr.json and downloads theme.mp3, however all mp3 get corrupted.

### Additional Context

Running latest linuxserver jellyfin image and nightly Themerr-jellyfin docker mod.
LOGS:
```
[2023-09-15 10:51:04.807 +01:00] [INF] [132] Jellyfin.Api.Controllers.UniversalAudioController: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: null, MaxAlbumArtHeight: null, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: 8000000, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "alac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "alac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "alac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: "", AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False, Conditions: [] }], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [] }
[2023-09-15 10:51:04.808 +01:00] [INF] [132] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "tiagalho". EnableAudioPlaybackTranscoding: True
[2023-09-15 10:51:04.850 +01:00] [INF] [10] Jellyfin.Api.Controllers.UniversalAudioController: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: null, MaxAlbumArtHeight: null, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: 8000000, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "alac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "alac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "alac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: "", AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False, Conditions: [] }], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [] }
[2023-09-15 10:51:04.852 +01:00] [INF] [10] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "tiagalho". EnableAudioPlaybackTranscoding: True
[2023-09-15 10:51:05.112 +01:00] [INF] [10] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.8.10" playing "theme". Stopped at "1097" ms
```

**Comment by ReenigneArcher** [comment] 2023-09-15 14:51
Please test if this is resolved in the `lizardbyte/themerr-jellyfin:nightly` mod.

**Comment by garlik82** [comment] 2023-09-15 15:11
Hi. I was already using nightly but I rebuilt the container clean the config folder, recreated my server and the same issue persists

**Comment by ReenigneArcher** [comment] 2023-09-15 15:17
Sorry, I missed that in your original issue.

Can you try this commit tag instead? [cb76597](https://hub.docker.com/layers/lizardbyte/themerr-jellyfin/cb76597/images/sha256-12f2055dccb7ad0bf8bb0f314b79d7bd9a6f20fb3e583aebf556087ddd2d716f?context=explore)

It that works then it might be a regression from #86

**Comment by ReenigneArcher** [comment] 2023-09-15 15:20
P.S. It's probably obvious, but you'll need to delete any themes for it to re-download them.

**Comment by garlik82** [comment] 2023-09-15 15:22
> Sorry, I missed that in your original issue.
> 
> Can you try this commit tag instead? [cb76597](https://hub.docker.com/layers/lizardbyte/themerr-jellyfin/cb76597/images/sha256-12f2055dccb7ad0bf8bb0f314b79d7bd9a6f20fb3e583aebf556087ddd2d716f?context=explore)
> 
> It that works then it might be a regression from #86

no dice. server is running on a Synology NAS if that is of any help.

**Comment by ReenigneArcher** [comment] 2023-09-15 15:28
Okay, I'm not sure how to replicate or resolve this at this point.

I wonder if it's an issue with transcoding. Hopefully Jellyfin isn't transcoding themes, but I'm not familiar with the inner workings of JF. Can you play the files in VLC media player?

**Comment by garlik82** [comment] 2023-09-15 15:30
I'll install a test container on my Mac to see if my Synology is the issue. Themes won't play on QuickTime.

**Comment by garlik82** [comment] 2023-09-15 15:45
Same issue running on Mac.

**Comment by garlik82** [comment] 2023-09-15 16:46
Installed native jellyfin Mac app, portable themerr-jellyfin, same thing. Checked the YouTube links on the json files and video plays.

**Comment by ReenigneArcher** [comment] 2023-09-15 17:24
Okay, I've reported this upstream to YoutubeExplode here: https://github.com/Tyrrrz/YoutubeExplode/issues/738

**Comment by ReenigneArcher** [comment] 2023-09-15 21:47
I think I discovered the issue. I don't think the file is actually corrupted, but I think it is downloading a `WebM` file instead of an `mp3` as it used to.

**Comment by garlik82** [comment] 2023-09-15 21:52
> I think I discovered the issue. I don't think the file is actually corrupted, but I think it is downloading a `WebM` file instead of an `mp3` as it used to.

you are correct, changed the extension from mp3 to webm and the file works.

**Comment by ReenigneArcher** [comment] 2023-09-15 22:04
I'm going to wait on a response from upstream to see if we can still directly get an mp3, otherwise I'll find a way to convert it.

**Comment by ReenigneArcher** [comment] 2023-09-15 23:07
@garlik82 do you mind testing this build?

https://github.com/LizardByte/Themerr-jellyfin/actions/runs/6203545632?pr=98

**Comment by garlik82** [comment] 2023-09-15 23:35
> @garlik82 do you mind testing this build?
> 
> https://github.com/LizardByte/Themerr-jellyfin/actions/runs/6203545632?pr=98

worked :)

**Comment by kiam001** [comment] 2023-10-25 09:04
Still issue on offical release

**Comment by ReenigneArcher** [comment] 2023-10-25 11:42
That's why the issue is still open.

**Closed** 2023-12-07 02:47 UTC
Labels: fixed
